"use client";

import { useState, useCallback, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { useAuth } from "@/contexts/auth-context";
import { useToast } from "@/components/ui/toast";
import { useTranslations } from "next-intl";
import { usePrintPreset } from "@/hooks/use-print-preset";
import { LabelForm, type LabelSaveData } from "@/components/labels/label-form";
import { type LabelPreviewData } from "@/components/labels/label-preview";
import { LabelPrint } from "@/components/labels/label-print";
import { PrintFlowModal } from "@/components/labels/print-flow-modal";
import { getPrintLayout } from "@/lib/print-style";
import { ArrowLeft, Info, Printer, Save } from "lucide-react";
import Link from "next/link";

const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === "true";
const LABEL_FORM_ID = "new-label-production-form";
type PreviewZoom = "fit" | 50 | 100;

export default function NewLabelPage() {
  const { getToken, hasActionPermission } = useAuth();
  const { toast } = useToast();
  const t = useTranslations("labels");
  const { preset, presetName, hasSavedPreset, presetLoaded, triggerPrint } = usePrintPreset();
  const searchParams = useSearchParams();

  const defaultProductId = searchParams.get("productId") || undefined;
  const defaultDate = searchParams.get("date") || undefined;

  const [previewData, setPreviewData] = useState<LabelPreviewData>({
    brand: "",
    productName: "",
    netContent: "--",
    productionDate: "",
    batch: "--",
    coldChain: "--",
    expiryRefrigerated: "--",
    expiryFrozen: "--",
    destination: "",
    packedBy: "",
    ingredients: "",
    allergens: "",
    storage: "",
    usage: "",
    qrData: "",
  });

  const [showPrintModal, setShowPrintModal] = useState(false);
  const [pendingSaveData, setPendingSaveData] = useState<LabelSaveData | null>(null);
  const [printData, setPrintData] = useState<LabelPreviewData | null>(null);
  const [previewZoom, setPreviewZoom] = useState<PreviewZoom>("fit");

  const canSave =
    hasActionPermission("labels", "crear") ||
    hasActionPermission("products", "rotular");
  const canPrint = hasActionPermission("labels", "imprimir");
  const canSaveAndPrint = canSave && canPrint;
  const layout = getPrintLayout(preset);
  const formatMm = (value: number) =>
    Number.isInteger(value) ? String(value) : value.toFixed(1);
  const profileLabel = [
    hasSavedPreset ? presetName : t("defaultPrintProfile"),
    `${formatMm(layout.pageWidthMm)} × ${formatMm(layout.pageHeightMm)} mm`,
    layout.pageWidthMm >= layout.pageHeightMm ? t("horizontal") : t("vertical"),
    `${preset.dpi} DPI`,
  ].join(" · ");

  // Ctrl+P follows the safe save-first flow so printed QR codes always point to
  // the opaque label ID generated by the server.
  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === "p" || e.key === "P")) {
        e.preventDefault();
        e.stopImmediatePropagation();
        if (previewData.productName && canSaveAndPrint) {
          const form = document.getElementById(LABEL_FORM_ID) as HTMLFormElement | null;
          form?.requestSubmit();
        }
      }
    };
    document.addEventListener("keydown", handleKeydown, { capture: true });
    return () => {
      document.removeEventListener("keydown", handleKeydown, { capture: true });
    };
  }, [canSaveAndPrint, previewData.productName]);

  const handlePreviewChange = useCallback((data: LabelPreviewData) => {
    setPreviewData(data);
    setPrintData(null);
  }, []);

  const handleSave = async (data: LabelSaveData) => {
    setPendingSaveData(data);
    setShowPrintModal(true);
  };

  const handlePrintConfirm = async (quantity: string) => {
    if (!pendingSaveData) return;

    const token = await getToken();

    if (DEMO_MODE) {
      setPrintData(previewData);
      toast({ title: t("saved"), variant: "success" });
      setShowPrintModal(false);
      setTimeout(() => triggerPrint(), 300);
      return;
    }

    if (!token) return;

    try {
      const labelRes = await fetch("/api/labels", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ ...pendingSaveData, quantityProduced: quantity }),
      });

      if (!labelRes.ok) {
        const err = await labelRes.json();
        toast({ title: err.error || "Error al guardar etiqueta", variant: "error" });
        return;
      }

      const savedLabel = await labelRes.json();
      const finalPrintData = {
        ...previewData,
        qrData: savedLabel.qrData || previewData.qrData,
      };
      setPreviewData(finalPrintData);
      setPrintData(finalPrintData);

      toast({ title: t("saved"), variant: "success" });
      setPendingSaveData(null);
      setShowPrintModal(false);
      setTimeout(() => triggerPrint(), 300);
    } catch {
      toast({ title: "No fue posible guardar la etiqueta", variant: "error" });
    }
  };

  const hasProduct = !!previewData.productName;

  return (
    <>
      <div className="mx-auto max-w-[1600px] print:hidden">
        <div className="mb-5 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <Link
              href="/labels"
              className="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-orange-600 transition hover:text-orange-700 dark:text-orange-400"
            >
              <ArrowLeft className="h-4 w-4" />
              {t("backToLabels")}
            </Link>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
              {t("newLabel")}
            </h1>
            <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
              {t("newLabelSubtitle")}
            </p>
          </div>

          <div className="inline-flex max-w-full items-center gap-2 self-start rounded-xl border border-orange-200 bg-orange-50 px-3.5 py-2.5 text-xs font-semibold text-orange-700 shadow-sm dark:border-orange-800/70 dark:bg-orange-500/10 dark:text-orange-300 xl:self-auto">
            <Printer className="h-4 w-4 shrink-0" />
            <span className="truncate">
              {presetLoaded ? `${t("activePrintProfile")}: ${profileLabel}` : t("loadingPrintProfile")}
            </span>
          </div>
        </div>

        <div className="grid items-start gap-5 xl:grid-cols-[390px_minmax(0,1fr)]">
          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <LabelForm
              formId={LABEL_FORM_ID}
              onPreviewChange={handlePreviewChange}
              onSave={handleSave}
              printConfigurationReady={presetLoaded}
              canSubmit={canSaveAndPrint}
              defaultValues={{
                productId: defaultProductId,
                productionDate: defaultDate,
              }}
            />
          </div>

          <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900 xl:sticky xl:top-4">
            <div className="flex flex-col gap-3 border-b border-slate-100 px-4 py-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between sm:px-5">
              <div>
                <h2 className="text-base font-semibold text-slate-900 dark:text-white">
                  {t("printPreview")}
                </h2>
                <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                  {formatMm(layout.pageWidthMm)} × {formatMm(layout.pageHeightMm)} mm · {t("adjustedView")}
                </p>
              </div>

              <div className="inline-flex self-start rounded-xl border border-slate-200 bg-slate-50 p-1 dark:border-slate-700 dark:bg-slate-800">
                {(["fit", 50, 100] as PreviewZoom[]).map((zoom) => {
                  const selected = previewZoom === zoom;
                  const label = zoom === "fit" ? t("fitPreview") : `${zoom}%`;
                  return (
                    <button
                      key={zoom}
                      type="button"
                      onClick={() => setPreviewZoom(zoom)}
                      aria-pressed={selected}
                      className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition ${selected ? "bg-white text-orange-600 shadow-sm ring-1 ring-slate-200 dark:bg-slate-700 dark:text-orange-300 dark:ring-slate-600" : "text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white"}`}
                    >
                      {label}
                    </button>
                  );
                })}
              </div>
            </div>

            <div className="flex min-h-[420px] items-center justify-center overflow-auto bg-slate-50/80 p-4 dark:bg-slate-950/40 sm:p-7">
              {hasProduct ? (
                <LabelPrint
                  data={previewData}
                  screenPreview
                  previewZoom={previewZoom}
                  preset={preset}
                />
              ) : (
                <EmptyPreview brand={previewData.brand} />
              )}
            </div>

            <div className="flex items-start gap-2 border-t border-slate-100 px-4 py-3 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400 sm:px-5">
              <Info className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" />
              <span>{t("previewPhysicalHint")}</span>
            </div>
          </section>
        </div>
      </div>

      {/* Only a server-saved label is exposed to the browser print surface. */}
      {printData && <LabelPrint data={printData} preset={preset} />}

      {/* Print quantity modal */}
      <PrintFlowModal
        open={showPrintModal}
        onClose={() => setShowPrintModal(false)}
        onConfirm={handlePrintConfirm}
        productName={previewData.productName}
      />
    </>
  );
}

function EmptyPreview({ brand }: { brand: string }) {
  const t = useTranslations("labels");

  return (
    <div className="w-full max-w-md rounded-2xl border border-dashed border-slate-300 bg-white/70 p-10 text-center dark:border-slate-700 dark:bg-slate-900/60">
      <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-50 dark:bg-orange-500/10">
        <Save className="h-6 w-6 text-orange-400 dark:text-orange-500" />
      </div>
      {brand && (
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-orange-400 dark:text-orange-500">{brand}</p>
      )}
      <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">
        {t("emptyPreviewTitle")}
      </p>
      <p className="mt-1 text-xs text-slate-400 dark:text-slate-500">
        {t("emptyPreviewHint")}
      </p>
    </div>
  );
}
